name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install dependencies (React project)
        run: |
          cd nom-du-projet-react
          npm install

      - name: Build React project
        run: |
          cd nom-du-projet-react
          npm run build

      - name: Deploy to Vercel
        run: |
          cd nom-du-projet-react
          vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --yes
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
