name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: List contents of the root directory
        run: ls -la

      - name: List contents of the React project directory
        run: ls -la nom-du-projet-react
      
      - name: Install dependencies (React project)
        run: npm install
        working-directory: nom-du-projet-react

      - name: Build React project
        run: npm run build
        working-directory: nom-du-projet-react

      - name: Deploy to Vercel
        run: vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --yes
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }} # Ajoutez cette ligne pour l'ID de l'organisation
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: nom-du-projet-react
